server:
  port: 8080

spring:
  profiles:
    include: Swagger2
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  data:
    elasticsearch:
      cluster-name: yanshi-es  #节点名字，默认elasticsearch
      cluster-nodes: 127.0.0.1:9300  #节点地址，多个节点用逗号隔开

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  global-config:
#    db-config:
#      id-type: uuid

logging:
  level:
    org:
      springframework: debug
#    root: debug
#    com.mp.dao: trace
#  pattern:
#    console: '%p%m%n'
